(define (problem tufox-instance)
  (:domain tufox)
  (:objects
    detective player bunny1 bunny2 bunny3 bunny4 - agent
    tower library armory observatory
    hall dining_room kitchen storage
    study throne_room bathroom bedroom
    chapel dungeon wine_cellar balcony - room
  )
  (:init
    (alive detective)
    (alive player)
    (at detective balcony)
    (at player hall)
    (connected tower library)
    (connected library tower)
    (connected library armory)
    (connected armory library)
    (connected armory observatory)
    (connected observatory armory)
    (connected hall dining_room)
    (connected dining_room hall)
    (connected dining_room kitchen)
    (connected kitchen dining_room)
    (connected kitchen storage)
    (connected storage kitchen)
    (connected study throne_room)
    (connected throne_room study)
    (connected throne_room bathroom)
    (connected bathroom throne_room)
    (connected bathroom bedroom)
    (connected bedroom bathroom)
    (connected chapel dungeon)
    (connected dungeon chapel)
    (connected dungeon wine_cellar)
    (connected wine_cellar dungeon)
    (connected wine_cellar balcony)
    (connected balcony wine_cellar)
    (connected tower hall)
    (connected hall tower)
    (connected library dining_room)
    (connected dining_room library)
    (connected armory kitchen)
    (connected kitchen armory)
    (connected observatory storage)
    (connected storage observatory)
    (connected hall study)
    (connected study hall)
    (connected dining_room throne_room)
    (connected throne_room dining_room)
    (connected kitchen bathroom)
    (connected bathroom kitchen)
    (connected storage bedroom)
    (connected bedroom storage)
    (connected study chapel)
    (connected chapel study)
    (connected throne_room dungeon)
    (connected dungeon throne_room)
    (connected bathroom wine_cellar)
    (connected wine_cellar bathroom)
    (connected bedroom balcony)
    (connected balcony bedroom)
    (fox player)
  )
  (:goal (inspected player))
)
